// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzpOD6Mm7D4A9M9WDbbjDu_FRgupaAne8',
    appId: '1:329435505112:web:bd108cf907721ecc0512ad',
    messagingSenderId: '329435505112',
    projectId: 'yummy-d0ecc',
    authDomain: 'yummy-d0ecc.firebaseapp.com',
    storageBucket: 'yummy-d0ecc.firebasestorage.app',
    measurementId: 'G-9P5GDPEHW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUVIFgiqLkREbYUo-9b5_ZSN8tjij1Isc',
    appId: '1:329435505112:android:31e26a4fea9b60860512ad',
    messagingSenderId: '329435505112',
    projectId: 'yummy-d0ecc',
    storageBucket: 'yummy-d0ecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa3InIOYNJRNrTj2Cd8E5cgcfdpWKeI9g',
    appId: '1:329435505112:ios:bd5673f615dcc6370512ad',
    messagingSenderId: '329435505112',
    projectId: 'yummy-d0ecc',
    storageBucket: 'yummy-d0ecc.firebasestorage.app',
    iosBundleId: 'com.example.yummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa3InIOYNJRNrTj2Cd8E5cgcfdpWKeI9g',
    appId: '1:329435505112:ios:bd5673f615dcc6370512ad',
    messagingSenderId: '329435505112',
    projectId: 'yummy-d0ecc',
    storageBucket: 'yummy-d0ecc.firebasestorage.app',
    iosBundleId: 'com.example.yummy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzpOD6Mm7D4A9M9WDbbjDu_FRgupaAne8',
    appId: '1:329435505112:web:b7dd5c5aa167246b0512ad',
    messagingSenderId: '329435505112',
    projectId: 'yummy-d0ecc',
    authDomain: 'yummy-d0ecc.firebaseapp.com',
    storageBucket: 'yummy-d0ecc.firebasestorage.app',
    measurementId: 'G-05SFZNNMH0',
  );
}
